src/objects/IntegrationDetail_CF__c.object
<CustomObject>
    <description>This object stores all the request and response bodies for each callout made on the system.</description>
    <fields>
        <fullName>Endpoint_CF__c</fullName>
        <description>The endpoint that has been invoked.</description>
        <inlineHelpText>The endpoint that has been invoked.</inlineHelpText>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LinkerId_CF__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Field which helps to relate request with response data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Field which helps to relate request with response data.</inlineHelpText>
        <label>Linker Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Integration Detail</label>
    <nameField>
        <displayFormat>ID-{00000000}</displayFormat>
        <label>Integration Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IntegrationEndpoint_CF__mdt.object
<CustomObject>
    <description>This object helps to store the Integration Endpoints per environment.</description>
    <fields>
        <fullName>AuthenticationToken_CF__c</fullName>
        <description>Field to provide Authentication Tokens.</description>
        <inlineHelpText>Field to provide Authentication Tokens.</inlineHelpText>
        <label>Authentication Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Endpoint_CF__c</fullName>
        <description>This field stores the Endpoint (URL or Named Credentials label).</description>
        <inlineHelpText>This field stores the Endpoint (URL or Named Credentials label).</inlineHelpText>
        <label>Endpoint</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

src/classes/HcscOAuthAccessControllerTest_ACE.cls
/**
* Test class for HcscOAuthAccessController_ACE.
* <p /><p />
* @author Rahul Nanda
*/
@isTest
public class HcscOAuthAccessControllerTest_ACE {
    public static string strRedirectUrl = ''; 
    public static string strRequestCode = '';
    public static Pagereference pageReference;
    
    public static testMethod void callThePageWithContinuation(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.GoogleLogin;
        
        //In this case, the Visualforce page named 'success' is the starting point of this test method. 
        Test.setCurrentPage(pageRef);
        //strRedirectUrl  = HcscOAuthAccessController_ACE.connect();
        Test.setCurrentPageReference(pageRef);
        HcscOAuthAccessController_ACE hcscCon = new HcscOAuthAccessController_ACE();
        test.startTest();
            HcscOAuthAccessController_ACE.getOAuthToken(system.currentPageReference().getParameters().get('code'));
        test.stopTest();
    }
    public static testMethod void connetMethod(){
       // List<GoogleConnectionSettings__mdt> cmdtLst = [Select DeveloperName,Value_ACE__c from GoogleConnectionSettings__mdt] ;
        //List<IntegrationEndpoint_CF__mdt > endPointLst = [SELECT Endpoint_CF__c, AuthenticationToken_CF__c FROM IntegrationEndpoint_CF__mdt]; 
        strRedirectUrl  = HcscOAuthAccessController_ACE.connect();
        Test.setCurrentPageReference(new pageReference(strRedirectUrl));
    }
    public static testMethod void getOAuthTokenMethod(){
        test.startTest();
      
        strRequestCode=System.currentPageReference().getParameters().get('code');
        
        //We first set the fake web service.
        Test.setMock(HttpCalloutMock.class, new IntegrationMockServiceLongRequestTest_CF());
        
        //Now we test a long request / response.
        String strLongRequest = '';
        
        Map<String, String> mapHeaderValues = new Map<String, String>();
        mapHeaderValues.put('test', 'test');
        for(Integer intCounter = 0 ; intCounter < 2000; intCounter++) {
            strLongRequest = strLongRequest + 'swat';
        }
        IntegrationClass_CF.synchronousCallout('Default', strLongRequest, false, mapHeaderValues, 120);
            IntegrationDetail_CF__c objIntegrationDetails = new IntegrationDetail_CF__c();
            objIntegrationDetails.LinkerId_CF__c = '1234';
            upsert objIntegrationDetails LinkerId_CF__c;
            IntegrationClass_CF.saveIntegrationDetails('1234', '', '', '');
            IntegrationClass_CF.futureCallout(null, null, null, null, null, null, null);
            System.assertNotEquals(null, objIntegrationDetails.Id, 'Record not inserted.');
            strRequestCode=apexpages.currentpage().getparameters().get('code');
        HcscOAuthAccessController_ACE.getOAuthToken(strRequestCode);
        Test.stopTest();
        
        
    }
}