src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TowerMapController.cls
/**
 * Description of the TowerMapUtilClass.
 * <p /><p />
 * @author Nagendra Kumar Singh
 */
public class TowerMapController {
    @AuraEnabled
    public static List<Tower__c> getAllTowers() {
        String theObject = 'Tower__c';
        List<String> theFields = new List<String>{
                'Id', 'Name', 'State__r.Name', 'Location__Latitude__s', 'Location__Longitude__s'
        };
        List<String> theFilters = new List<String>();  //empty filter list
        String sortField = 'Name';
        String sortOrder = 'ASC';
        List<Tower__c> allTowers = new List<Tower__c>();
        return allTowers;
    }
}